### ISSUE TITLE
小键盘不能用可以参考下这一篇文章

### ISSUE THREAD

**Issue by yanyumihuang** [happylzyy/Hackintosh-Lenovo-R720#1]
[小键盘](https://blog.csdn.net/dale042/article/details/109766523)
就是我用他的oc，能进系统但显示屏灰屏，按键有反应

**Comment by happylzyy** [comment]
非常感谢你的建议。
你提供的这篇文章的作者和我在同一个QQ群，小键盘的问题我们在群里讨论过。
对于键盘来说，目前有两种驱动方案，一是VoodooPS2Controller，二是ApplePS2SmartTouchPad。前者是最近发布的新驱动，可以解锁触控板的所有手势，但是R720小键盘不能用；后者是以前用的旧驱动，对触控板的支持不好，但是小键盘可以用。因为这篇文章的作者换回了原来的旧驱动，所以他的OC小键盘可以用，严格来说小键盘问题在新驱动中并没有被修复。
这两个kext在我的项目中都包含了，可以在config.plist中二选一，目前完美的触控板功能和小键盘不能兼得。如果有其他对项目改进有帮助的信息，欢迎来这里分享。

**Comment by yanyumihuang** [comment]
确实小键盘不能用，但我经过测试发现其实是numlock键没有其作用，使用voodoops2之后小键盘的功能就变成了上面印的了。.这个键变成了delete键，，8这个键变成了音乐播放的暂停与开始。我使用了voodoops2提供的映射的方法，将1，2，3，4，5，6，8，9，0键映射到了f1到f12下面的那一排数字键上。但数字键盘上的7按一下等于同时按下左shift 左control，还有其本身，我没办法处理，还有.这个键，因为在主键盘上是没有单独的.这个键映射也是很失败的。在中文状态下按下去是。英文状态下是.[映射的方法点这里](http://www.yekki.me/how-to-mapping-keys-on-ps2/)，我自己映射的文件在这里，注释是瞎写的。我也就能弄到这一步了，过两天我就自己关了这个issue了，另外老哥能拉我进群吗？我申请了好几次都没人同意，昵称叫烟雨弥凰
![image](https://user-images.githubusercontent.com/26965886/102689050-3a607800-4236-11eb-9363-4578efd501ae.png)

**Comment by yanyumihuang** [comment]
补充一下，在iterm2中这样的映射是完全可用（不管是中文还是英文输入法）的，数字7和.键是完全可用，但在其他app中不行
![image](https://user-images.githubusercontent.com/26965886/102704762-5b6aac80-42ba-11eb-81ec-514de0430d78.png)上面是中文输入，下面是英文输入法

**Comment by happylzyy** [comment]
> 确实小键盘不能用，但我经过测试发现其实是numlock键没有其作用，使用voodoops2之后小键盘的功能就变成了上面印的了。.这个键变成了delete键，，8这个键变成了音乐播放的暂停与开始。我使用了voodoops2提供的映射的方法，将1，2，3，4，5，6，8，9，0键映射到了f1到f12下面的那一排数字键上。但数字键盘上的7按一下等于同时按下左shift 左control，还有其本身，我没办法处理，还有.这个键，因为在主键盘上是没有单独的.这个键映射也是很失败的。在中文状态下按下去是。英文状态下是.[映射的方法点这里](http://www.yekki.me/how-to-mapping-keys-on-ps2/)，我自己映射的文件在这里，注释是瞎写的。我也就能弄到这一步了，过两天我就自己关了这个issue了，另外老哥能拉我进群吗？我申请了好几次都没人同意，昵称叫烟雨弥凰
> ![image](https://user-images.githubusercontent.com/26965886/102689050-3a607800-4236-11eb-9363-4578efd501ae.png)

好的，我再研究一下，看看能不能全部映射。我不是那个群的管理员，没法拉你进群

**Comment by yanyumihuang** [comment]
好的，那我就把这个issue关了

**Comment by happylzyy** [comment]
> 好的，那我就把这个issue关了

最近有大佬解决了小键盘不能用的bug，最新编译的VoodooPS2Controller和对应的SSDT修补已经上传

**Comment by yanyumihuang** [comment]
> 最近有大佬解决了小键盘不能用的bug，最新编译的VoodooPS2Controller和对应的SSDT修补已经上传
我用的是clover，因为不管是谁的oc我用都用问题，屏幕不亮（可能幸好不一样，我的大型号也是R720，但我是17年初买的，显卡也是1050，不知道哪里不一样）。然后我下载了你的ssdt的kets，放进clover里面，但并没有生效。请问您是在哪里看到这个ssdt的？

**Comment by happylzyy** [comment]
> > 最近有大佬解决了小键盘不能用的bug，最新编译的VoodooPS2Controller和对应的SSDT修补已经上传
> 
> 我用的是clover，因为不管是谁的oc我用都用问题，屏幕不亮（可能幸好不一样，我的大型号也是R720，但我是17年初买的，显卡也是1050，不知道哪里不一样）。然后我下载了你的ssdt的kets，放进clover里面，但并没有生效。请问您是在哪里看到这个ssdt的？
> 
> 

来自README参考资料第三个，最新编译的voodooPS2Contoller解决了小键盘不能用的bug
