### ISSUE TITLE
How do I change the installation language?

### ISSUE THREAD

**Issue by vfxbro** [happylzyy/Hackintosh-Lenovo-R720#12]

**Comment by happylzyy** [comment]
Change the NVRAM variable associated with installation language. The variable is in the `config.plist` file. The path is `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd`.
This is an ASCII string defining default keyboard layout. Format is lang-COUNTRY:keyboard, e.g. ru-RU:252 for Russian locale and ABC keyboard. Also accepts short forms: ru:252 or ru:0 (U.S. keyboard, compatible with 10.9). Full 61 decoded keyboard list from AppleKeyboardLayouts-L.dat can be found [here](https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/AppleKeyboardLayouts). Using non-latin keyboard on 10.14 will not enable ABC keyboard, unlike previous and subsequent macOS versions, and is thus not recommended in case 10.14 is needed.
After changing the variable, the installation language will change, if the configuration does still not take effect, you may need to reset the NVRAM.

**Comment by vfxbro** [comment]
thx!
