### ISSUE TITLE
Won't start without USB

### ISSUE THREAD

**Issue by vfxbro** [happylzyy/Hackintosh-Lenovo-R720#13]
After a successful installation I have everything booted normally, but there is a problem, when I remove the installation USB from the laptop, I have no MacOS to boot.
If I insert the flash drive, it boots successfully.

**Comment by happylzyy** [comment]
Since MacOS is loaded by the OpenCore bootloader, you need to copy the EFI file to the esp partition of your local disk, which is usually the first partition in the partition list. Then insert the opencore boot entry into the UEFI boot entry list.

**Comment by vfxbro** [comment]
thx!
