### ISSUE TITLE
替换了AX200,使用itlwm或者AirportItlwm，还是不能驱动wifi，需要删除本地什么kexts吗

### ISSUE THREAD

**Issue by liudaoxiaozi** [happylzyy/Hackintosh-Lenovo-R720#18]

**Comment by liudaoxiaozi** [comment]
安装完系统后，系统自带wifi图标，是不是有驱动了，冲突了，那之前EFI文件中网卡驱动是哪个呢，或者修改config.plist什么部位配置呢，我要使用自己的网卡

**Comment by happylzyy** [comment]
EFI里没有无线网卡驱动，自己替换的无线网卡需要自己驱动。
ax200驱动方法请查看官方文档：https://openintelwireless.github.io/General/Installation.html

**Comment by liudaoxiaozi** [comment]
嗯，谢谢
