### ISSUE TITLE
使用U盘启动后，出现一个硬盘的图标和windows一样，然后他就会启动windows啦。请问下有解决方案嘛？谢谢

### ISSUE THREAD

**Issue by lajiao1874** [happylzyy/Hackintosh-Lenovo-R720#19]
![image](https://user-images.githubusercontent.com/77315337/227709483-6a4a42fe-cff1-478f-aa1e-3e79ec929fce.jpeg)![image](https://user-images.githubusercontent.com/77315337/227709496-7fefb50d-c2e1-4729-837d-5cb3ed493166.jpeg)

**Comment by happylzyy** [comment]
调整一下config里的scanpolicy，置0可扫描全部存储设备分区

**Comment by lajiao1874** [comment]
好的，我试试，谢谢
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 happylzyy ***@***.***>发送时间: 星期六, 三月 25, 2023 20:26收件人: happylzyy/Hackintosh-Lenovo-R720 ***@***.***>抄送: liyoung1874 ***@***.***>; Author ***@***.***>主题: =?UTF-8?B?UmU6IFtoYXBweWx6eXkvSGFja2ludG9zaC1MZW5vdm8tUjcyMF0g5L2/55SoVeebmOWQr+WKqOWQju+8jOWHuueOsOS4gOS4quehrOebmOeahOWbvuagh+WSjHdpbmRvd3PkuIDmoLfvvIznhLblkI7ku5blsLHkvJrlkK/liqh3aW5kb3dz5ZWm44CC6K+36Zeu5LiL5pyJ6Kej5Yaz5pa55qGI5Zib77yf6LCi6LCiIChJc3N1ZSAjMTkp?= 
调整一下config里的scanpolicy，置0可扫描全部存储设备分区

**Comment by lajiao1874** [comment]
修改了您说的配置之后出现了Efi 选项，不过选择了之后进入黑屏

**Comment by lajiao1874** [comment]
![image](https://user-images.githubusercontent.com/77315337/227750430-b89612c8-34b5-4bdb-910d-63dbda70d090.jpeg)

**Comment by happylzyy** [comment]
> ![image](https://user-images.githubusercontent.com/77315337/227750430-b89612c8-34b5-4bdb-910d-63dbda70d090.jpeg)

有安装macOS系统吗

**Comment by lajiao1874** [comment]
没有，点击EFI之后进入的是黑屏

**Comment by happylzyy** [comment]
> 没有，点击EFI之后进入的是黑屏
MacOS安装教程
https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html

**Comment by lajiao1874** [comment]
谢谢，我试试这个，我原本使用的是这个教程
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos

**Comment by lajiao1874** [comment]
有个问题请教下。我下载下来的镜像是ISO格式的，这格式对嘛？因为我在使用echer 刻录的时候它提示如图。![image](https://user-images.githubusercontent.com/77315337/228282740-8b15c8d8-5282-4fad-843e-e244307ec8cf.jpeg)

**Comment by happylzyy** [comment]
应该没事吧 试试能不能用

**Comment by lajiao1874** [comment]
试过了，能刻录完成，不过刻录完之后 U 盘里啥也没有

**Comment by happylzyy** [comment]
正常，Windows不能识别镜像里的苹果文件系统分区。电脑重启，bios选择u盘启动，看能不能装macOS

**Comment by lajiao1874** [comment]
好的，谢谢。我晚上试试。
这样是否会存在一个问题，因为无法看见 EFI 文件，所以无法将 serial ID 之类的值写入到 config.list 中，这样对安装不会有影响嘛 ？
还是说，可以等安装了 MacOS 之后再将 serial ID 之类的数据补充进 config.list 中就可以 ？

**Comment by happylzyy** [comment]
安装好了再配置efi也可以，因为安装镜像自带的efi应该就够用了

**Comment by lajiao1874** [comment]
不行的，使用U盘启动，U盘读不出来

**Comment by happylzyy** [comment]
再看看吧，网上很多macOS安装教程

**Comment by lajiao1874** [comment]
嗯，很感谢啦
