### ISSUE TITLE
Sequoia 亮度调节

### ISSUE THREAD

**Issue by AlanSmith111** [happylzyy/Hackintosh-Lenovo-R720#23]
你好请问你在安装 Sequoia 之后亮度调整能否正常使用，谢谢。我这边调不了了，调节亮度没有反应，亮度调到 0 黑屏。也是同样的机型 15IKBN

**Comment by happylzyy** [comment]
我这里的亮度调节是正常的，建议用EFI整个替换

**Comment by AlanSmith111** [comment]
好的谢谢。
