### ISSUE TITLE
从10.15 升级到BigSur后核显驱动不成功

### ISSUE THREAD

**Issue by DreamSaddle** [happylzyy/Hackintosh-Lenovo-R720#3]
你好，我使用你这个EFI，核显一直驱动不成功，请问有什么解决办法吗？

安装过程中只能把平台ID设置为`12345678`才能进入系统，安装完成后再把平台ID改为原来的值跑完后就黑屏，进不去系统。

**Comment by DreamSaddle** [comment]
显存7M问题，我在网上找了一些办法都没奏效。

**Comment by happylzyy** [comment]
开机启动内核参数加-v，看看错误日志

**Comment by DreamSaddle** [comment]
> 开机启动内核参数加-v，看看错误日志

@happylzyy 谢谢回复！！！
我加了试过，一开始是正常的跑码，过后黑屏了，我猜就是平台ID或其他配置的问题导致的。
主要是它最后那点跑码速度很快，看不到

**Comment by happylzyy** [comment]
设置一下内核恐慌不自启，就能看到错误日志了
________________________________

**Comment by DreamSaddle** [comment]
@happylzyy 请问这个是怎么设置的呢？😁

**Comment by happylzyy** [comment]
看了一下配置文件好像没有那个选项了，我也不清楚，在网上搜搜看看吧

**Comment by xscit** [comment]
仿冒成HD530就不会黑屏了。
![image](https://user-images.githubusercontent.com/26691690/142769314-48ad3bff-5feb-4e51-9b20-cc7914c0aa06.png)
![image](https://user-images.githubusercontent.com/26691690/142769337-714b4ba4-8d26-4d69-a4df-c9038d2666e3.png)

**Comment by DreamSaddle** [comment]
@xscit 你好。请问你也是相同的配置吗？如果是可否方便提供一下EFI呢？
我上次安装就是核显没驱动，一致仿冒的其它ID，一致不成功。

谢谢！

**Comment by DreamSaddle** [comment]
> 

我安装的时候就进不去，就会黑屏，只有把平台ID修改为`12345678`才能进行安装。

**Comment by xscit** [comment]
@DreamSaddle 按我图片上的改下平台id，设备id，启动参数加上lilucpu=8就行了。

**Comment by DreamSaddle** [comment]
@xscit 好的，谢谢！

**Comment by DreamSaddle** [comment]
@xscit 你好，忘记问你的机型选择的是哪一个呢？

**Comment by DreamSaddle** [comment]
@xscit 你好，十分感谢提供平台ID及设备ID数据。今天替换后直接就安装成功了。核显正常驱动。
 @happylzyy  感谢！其余也成功驱动。

另外 HDMI 通过将将机型设置为 `MacBookPro11,4` 即可解决。另外三码正常注入。

**Comment by Haozi0456** [comment]
你好，我也遇到这个问题，能把你的EFI分享给我一份吗？ 谢谢

**Comment by DreamSaddle** [comment]
@Haozi0456 可以呀，把你邮件给我吧。

**Comment by Haozi0456** [comment]
468164865@qq.com

**Comment by Haozi0456** [comment]
> @Haozi0456 可以呀，把你邮件给我吧。

468164865@qq.com

**Comment by DreamSaddle** [comment]
@Haozi0456 已发送给你了。
