### ISSUE TITLE
mac12.0.1，核显无法驱动，屏幕亮度无法调节

### ISSUE THREAD

**Issue by symmets** [happylzyy/Hackintosh-Lenovo-R720#4]
试了很多核显的仿冒id，但显存始终显示为7m，无法驱动，尝试使用hackintool生成核显补丁，会导致卡代码。大佬有无解决办法？

**Comment by happylzyy** [comment]
提供的信息不够，我也不清楚你的问题出在在哪里。
可以尝试一下替换整个efi，机型三码信息用OC Configurator生成，使用macbook14,3机型。

**Comment by happylzyy** [comment]
另外可以看看这个https://github.com/happylzyy/Hackintosh-Lenovo-R720/issues/3

**Comment by symmets** [comment]
十分感谢，仿冒hd530，使用0x191b0000，lilucpu=8后，问题成功解决。

**Comment by DreamSaddle** [comment]
哈哈，看来都有这个问题呀。
