### ISSUE TITLE
颜色描述文件不对

### ISSUE THREAD

**Issue by DreamSaddle** [happylzyy/Hackintosh-Lenovo-R720#5]
### 内建显示器文字颜色显示不对

比如 `#f97bb0` 这个颜色，在我的内建显示器（笔记本这个）和外接显示器显示效果不一样。
主要对比一下`import`关键字，内建显示器的颜色要泛白、浅一些。
我在系统设置的显示器设置更换 颜色描述文件 也没用，所以，想请教一下这里是不是与EFI有关呀？

#### 内建显示器
![image](https://user-images.githubusercontent.com/31559386/146112451-2c8cf319-8f56-4d01-8d1d-71b5d2760c3c.png)

#### 外接显示器
![image](https://user-images.githubusercontent.com/31559386/146112499-7b3a6155-3b27-4395-863c-826332ec7307.png)

**Comment by happylzyy** [comment]
不同的显示器内置了不同的颜色配置文件，通常是出厂时校准过的，想要解决偏色问题可以试试校色仪重新生成颜色配置文件
