### ISSUE TITLE
更换了带hdmi的机型smbios还是无法使用hdmi 

### ISSUE THREAD

**Issue by asnf09** [happylzyy/Hackintosh-Lenovo-R720#6]
试过使用opencore configurator选择macbookpro11.5,macbook14.2,都无法使用hdmi，请大神指教

**Comment by happylzyy** [comment]
我现在用的是Monterey系统，尝试修改成macbook11,2无法启动，可能是这个版本不再支持旧机型了。
以前版本的macOS可以通过改成macbook11,2来开启HDMI。
ps.改机型的时候记得三码也相应要改

On Feb 3, 2022, at 12:14 PM, asnf09 ***@***.***> wrote:

﻿

试过使用opencore configurator选择macbookpro11.5,macbook14.2,都无法使用hdmi，请大神指教

**Comment by happylzyy** [comment]
可以试试这个方法
https://github.com/happylzyy/Hackintosh-Lenovo-R720/issues/7
