### ISSUE TITLE
hdmi外接显示器没有反应

### ISSUE THREAD

**Issue by pistachioRain** [happylzyy/Hackintosh-Lenovo-R720#7]
装好big sur以后，其他都正常，但是通过hdmi接口连接外部显示器，没有任何反应，这个应该咋弄

**Comment by happylzyy** [comment]
目前已知有三个解决HDMI问题的方法：
1. 如果使用的是旧版本系统，比如Big Sur或更早的版本，可以尝试将SMBIOS机型修改成带有HDMI接口的机型,比如改成`macbook11,2` ，相应的三码也要重新生成。
2. 直接修改AppleGraphicsDevicePolicy或Kext to Patch，参考https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1848596
3. 修改Config中显卡的配置参数，可以参考这篇文章https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html

我没有外置显示器，所以不能对HDMI输出进行测试，如果你通过上述三种方法之一或者其他方法修改成功了，欢迎共享交流！

**Comment by DreamSaddle** [comment]
@pistachioRain 你好，我这边是安装的 Monterey，hdmi 能正常使用。首次插入可能会没用，再次拔掉后插入就可以了。
能 Monterey 何必 BigSur 呢。升上来吧。😁

**Comment by DreamSaddle** [comment]
@pistachioRain HDMI 通过将将机型设置为 MacBookPro11,4 即可解决。另外三码正常注入。
#3

**Comment by happylzyy** [comment]
> @pistachioRain HDMI 通过将将机型设置为 MacBookPro11,4 即可解决。另外三码正常注入。
> 
> #3 

设置成这个机型之后，随航和通用控制的功能还在吗？

**Comment by DreamSaddle** [comment]
> > @pistachioRain HDMI 通过将将机型设置为 MacBookPro11,4 即可解决。另外三码正常注入。
> > #3
> 
> 设置成这个机型之后，随航和通用控制的功能还在吗？

没有了，我没用到这两个功能。

**Comment by happylzyy** [comment]
> > > @pistachioRain HDMI 通过将将机型设置为 MacBookPro11,4 即可解决。另外三码正常注入。
> 
> > > #3
> 
> > 
> 
> > 设置成这个机型之后，随航和通用控制的功能还在吗？
> 
> 
> 
> 没有了，我没用到这两个功能。

OK，推了新的commit，另外加了一个featureunlock.kext，可以在改机型后解锁随航和通用控制
