### ISSUE TITLE
BCM94352Z无法使用BrcmFirmwareData等kext

### ISSUE THREAD

**Issue by KeUis** [happylzyy/Hackintosh-Lenovo-R720#8]
向设备属性设置添加了网卡条目。添加BrcmFirmwareData，BrcmBluetoothInjector，BrcmPatchRAM3这三个kext之后无法引导，请问是kext的问题还是OS12的问题

**Comment by KeUis** [comment]
报错文字识别大体是`922-85-18 08:44:41.792218 (system/cam.apple.locatlond.[657) Noticey: extted due to extt(6y 822-85-10 08:44:41.792221 (systen/com.apple.locat land [65]) alotice): service state:"extted 

922-85-10 98:14:41.792214 (systen/com.apple.locatland [651)Notice>: servlce extted: dirty "".'suppol ted pressured-extt =g 

92285-19 98:14:39.369189(system/cam.apple.trustdFlleHelpert9g7）/iottcsy: sarvice state: not ruuntng 

:022-05-10 08:44:41.792245 (system) <Notlce>: servlce tnactlve: com.apple.lacatlond 

922-85-10 08:44:41.792224 (system/com.apple.locatland [65]) <Notice>: internat event: EXITED, cade =@:922-05-10 08:44:41.792227 (system/com.apple.locatlond [65]) Notlce): jab state = exited 

8951999:11:15.191398 ysten' Haming?: falled activat lon: nene a com.apple.lsd.persamntserver. flags - od, requestor=Lsd[197]. ernror - 37: Qperatlon already tn pragress 29295-19 99:14:15.16i7n0 systen? suarning?: fatled loolap: nane= can.appte.nobtte.keybagd.usertanederee. ags e se. requestaratsacten.aeo ae 

:822-85-18 08:44:41.792266 (systen/com.apple.locat lond [65]) (Noticey: service state: not rumning 

2922-85-18 88:44:32-3oag70 (systen) larntng?: Falled lookup: nane =com.apple.coreservices.quaranttne-rasolver,requestar = softwareupdated[521, error= 3: No such pracess 2922-95-19 08:14:55.324216 (systen) Warntng>: fatled actlvat lon: nane = com.apple.lsd.personaobserver. flags ='ax@, requestar = Lsd[1871, errar's 37: Qperatlan atready un progress 2822-85-10 98:11:55.924896 (systen) dlarnung?: falled lookup: name = com.apple.moblle.keybagd.UserHanager.xpc. flags = ax8, requestor=tsd[1871, errare 3: No sucn process 

292395-19 99:14:15.a7izag systen? Harming?: Called lockup: name = cam.apple.syste-.apendtrectarya.libtifo.'rtags'= axe.'requastor- crprersatisi.'errorgeio suar pracess 2022-05-18 08:44:48.793562 <Notlce>: Flushed 189 Logs [llmlt：20]

2022-05-10 08:45:06.1981502022-05-10 08:45:06.1991882022-05-10 88:45:08.535986

| (systen) Marning?: falled actlvat ion: nane = com.apple. lsd.personaobserver. flags'= @x6, requestar - Lsd[1071. error's 37: Operat ton already un progress ! (system) Warntng>: fat led lookup: name = com.apple.moblle.keybagd.UserHanager.xpc. flags = @x8, requestor = lsd[1871, error = 3: No such process 

2022-05-10 08:45:88.536004 (system/com.apple.bsd.dirhelper [69]) <Notlce>: extted due to exlt(8)2022-05-10 08:45:08.536808 (systen/com.apple.bsd.dirhelper [69])<Notlce>:servlce state: exlted 

i (system/com.apple.bsd.dirhelper [69]) <Notice>: service exlted: dirty = 0, supported pressured-exlt = 1

2922-05-10 08:45:08.536012 (system/com.apple.bsd.dtrhelper[69])<Notlce>:lnternal event: EXITED,code =012022-05-18 08:45:08.536014 (system) <Notice>: service tnactlve: com.apple.bsd.dlrhelper 

|2822-05-10 08:45:16.216166 (system) <Warning>: fal led actlvat lon: nane = com.apple. lsd.personaobserver. flags = @x8, requestor = lsd[107], error = 37: Operat ton already tn progress |2922-05-18 08:45:16.217222 (system) (Warning>: fat led lookup: name = com.apple.mablle.keybagd.UserManager.xpc. flags = @x8, requestor = Lsd[1871, error s 3: No such process 

|2822-85-10 08:45:08.536029 (system/com.apple.bsd.dirhelper [691) <Notice>: servlce state: not runntng 

|2022-05-10 08:45:48.259684 (systen/com.apple.systemkeychaln [116]) <Notice>: exlted due to exit(@)|2022-05-18 08:45:40.259608 (system/com.apple.systenkeychatn[1161) <Notice>:servlce state: exi ted 

|2022-05-10 08:45:48.259572 (systen/com.apple.systemkeychaln[116]) <Notlces: servlce exlted: dirty=0, supported pressured-exlt = 1

|2822-05-18 88:45:48.259613 (systen/com.apple.systenkeychatn[1161) <Notice>:internal event: EXITED, code = 0|2822-05-10`

**Comment by happylzyy** [comment]
这个可能是Monterey12系统的问题，论坛里有说12系统wifi蓝牙出问题的，[bcm94352z在monterey wifi无法驱动](https://bbs.pcbeta.com/viewthread-1909902-1-1.html)。我的网卡是BCM94360CS2，所以没法测试BCM94352Z，这个EFI也没有加BCM94352Z的驱动。
链接里提供了驱动的方法，[bcm94352z网卡 在macos 12.0驱动方法](https://bbs.pcbeta.com/viewthread-1895450-1-1.html)，如果驱动成功欢迎PR

**Comment by KeUis** [comment]
谢谢，确实解决了，赞美
