### ISSUE TITLE
合盖睡眠不正常 

### ISSUE THREAD

**Issue by Aliang1337** [happylzyy/Hackintosh-Lenovo-R720#9]
合盖睡眠不正常  合盖后再次打开 盖子 电脑异常卡吨 或者直接就醒不来1了

**Comment by Aliang1337** [comment]
BigSur 版本的

**Comment by happylzyy** [comment]
> BigSur 版本的
> 
> 

我这里已经测试过可以用的。
可能还需要更多的细节来定位问题，比如笔记本配置，是否换过硬件，详细的错误代码。
目前来看可能的原因是系统安装的时候efi没有正确替换。
在系统镜像刻录到U盘后，需要手动替换掉U盘的efi才能正确安装，系统安装完成后再将efi复制到系统盘EFI分区。

**Comment by Aliang1337** [comment]
我现在尝试升级到12系统 出现卡在100的问题 卡好久都不动，大佬是否能看出问题？
![image](https://user-images.githubusercontent.com/35387465/177288264-12067080-408d-4b08-afca-f36de0e6c63f.png)
![image](https://user-images.githubusercontent.com/35387465/177288269-74e4692a-5261-4ba7-9c17-ef3f47b560f1.png)

**Comment by Aliang1337** [comment]
我换的硬件网卡是 DW1820A 不知道会不会有什么影响

**Comment by happylzyy** [comment]
> 我换的硬件网卡是 DW1820A 不知道会不会有什么影响

DW1820A换上之后需要在efi里加驱动，否则系统会崩溃，系统检测到这个网卡没有驱动就会卡住。
还有同一型号的这种卡有的能驱动有的不能。

**Comment by Aliang1337** [comment]
我已经禁用了 网卡 和驱动 升级还是卡在这里 我现在也不知道为什么了 
对了我的系统是装在外置固态中了 ！

**Comment by happylzyy** [comment]
> 我已经禁用了 网卡 和驱动 升级还是卡在这里 我现在也不知道为什么了 
> 
> 对了我的系统是装在外置固态中了 ！

网卡要拔掉，会影响开机。系统装在外置固态问题应该不大，另外三星的某些型号固态不兼容macOS
